[workspace]
resolver = "2"
members = ["core"]


[workspace.dependencies]
chrono = "0.4.38"
tokio = { version = "1.37.0", features = ["full"] }
thiserror = "1.0.59"
futures = "0.3.30"
rstest = "0.19.0"