# TOKEN TO TRADE INFORMATION

token:
  name: Token 1
  symbol: TKN
  decimals: 8
  address: 0x11111111111111111111111111111111
  # Community information to pull data from this threads / accounts
  community:
    reddit:
    discord:
    telegram:
    twitter:

bot:
  # Amount of SOL bet
  bet: 0.02
  # Slippage tolerance: 0 -> 1 (0% to 100%)
  slippage: 0.2
  # SOL gas fee for each transaction
  priority_fee: 0.00005

  metrics:
    - name: EMA1
      type: EMA
      period: 2

  orders:
    # List Stop Loss Orders to automate Buy and Sell
    stopLoss:
      - type: fixed
        # Price floor in SOL
        floor: 0.0001
      - type: trailing
        # Drop max for the highest price acheived: 0 -> 1 (0% -> 100%)
        drop: 0.1
      - type: performance
        # Profit aimed: 0 -> 1 (0% -> 100%)
        profit: 1.5
      - type: time
        # Duration to idle before selling (in seconds)
        duration: 100000

node:
  provider: QUICKNODE / MAINNET
  url: ""
