[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
